name: Build
on: [push]

jobs:

  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Latest
        run: docker build -t ${{ github.repository_owner }}/gocover:latest .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [dockerize]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Latest
      run: docker build -t ghcr.io/${{ github.repository_owner }}/gocover:latest .

    - name: Tag Unstable
      run: docker tag ghcr.io/${{ github.repository_owner }}/gocover:latest ghcr.io/${{ github.repository_owner }}/gocover:unstable

    - name: Push Unstable
      run: docker push ghcr.io/${{ github.repository_owner }}/gocover:unstable

    - name: Push Latest
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push ghcr.io/${{ github.repository_owner }}/gocover:latest

    - name: Tag Version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag ghcr.io/${{ github.repository_owner }}/gocover:latest ghcr.io/${{ github.repository_owner }}/gocover:${GITHUB_REF/refs\/tags\//}

    - name: Push Tag
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push ghcr.io/${{ github.repository_owner }}/gocover:${GITHUB_REF/refs\/tags\//}
